export const en = {
    // Global & Header
    appTitle: "Elastic/OpenSearch",
    appSubtitle: "Sizing Calculator",
    appDescription: "A premium technical tool to accurately estimate storage, memory, and instances required for your OpenSearch & Elasticsearch data architectures.",
    howIsCalculated: "How is this calculated?",

    // Progress & Navigation
    sizingProgress: "Sizing Progress",
    btnBack: "Back",
    btnContinue: "Continue",
    btnExport: "Export / Print",
    btnViewArchitecture: "View Architecture",

    // Step names
    stepUserInfo: "User Information",
    stepGlobalSettings: "Global Settings",
    stepAdvancedConfigs: "Advanced Configs",
    stepHotTier: "Hot Tier",
    stepWarmTier: "Warm Tier",
    stepColdTier: "Cold Tier",
    stepFrozenTier: "Frozen Tier",
    stepArchitecture: "Architecture",
    stepResults: "Results Dashboard",

    // Tier Names
    hotTier: "Hot",
    warmTier: "Warm",
    coldTier: "Cold",
    frozenTier: "Frozen",

    // User Information
    userInfoTitle: "User Information",
    userInfoSubtitle: "Please provide your contact information to continue.",
    nameLabel: "Full Name",
    namePlaceholder: "Enter your full name",
    nameDesc: "Your name for identification purposes",
    emailLabel: "Email Address",
    emailPlaceholder: "your.email@example.com",
    emailDesc: "Valid email address for contact",
    emailInvalid: "Please enter a valid email address",
    termsLabel: "I agree to the",
    termsLink: "Privacy and Use Terms",
    termsRequired: "You must accept the terms to continue",

    // Global Settings
    globalTitle: "Global Cluster Settings",
    globalSubtitle: "Define the core limits and which data tiers your cluster will support.",
    maxMemoryLabel: "Max Memory per Node (GB)",
    maxMemoryDesc: "Usually 64GB due to JVM limits",
    growthLabel: "Organic Growth (%)",
    growthDesc: "Buffer for expected data growth",
    activeTiersLabel: "Active Data Tiers",
    activeTiersDesc: "Select which data temperatures your architecture will contain",

    // Advanced Configs
    advTitle: "Advanced Size Configurations",
    advSubtitle: "Customize the GB Storage to GB RAM ratios and shard limits. Default values are recommended by Elastic.",
    ratioLabel: "Storage to RAM Ratio (GB)",
    ratioDesc: "How many Gigabytes of Storage are supported per 1 Gigabyte of RAM in each tier?",
    tierRatioSuffix: "Tier Ratio",
    maxShardTitle: "Maximum Shard Size",
    maxShardDesc: "Defines the max storage capacity before a shard splits. This determines the Total Shard count parameter.",
    sizePerShard: "Size per Shard (GB)",

    // Tier Settings
    tierTitlePrefix: "",
    tierTitleSuffix: "Tier Sizing",
    tierSubtitle: "Configure ingestion and retention for this specific data tier.",
    volLabel: "Daily Ingestion Volume (GB)",
    volDesc: "Amount of raw data ingested per day",
    volDescSynced: "Synced with Hot tier volume",
    retentionLabel: "Retention / Lifecycle (Days)",
    retentionDesc: "How long data stays in this tier",
    replicasLabel: "Number of Replicas",
    replicasDesc: "Additional copies of each primary shard",

    // Architecture Nodes
    archTitle: "Management Nodes",
    archSubtitle: "Optionally allocate dedicated instances for cluster management and coordination.",
    nodesCount: "Instances",
    diskSize: "Disk Size (GB)",
    ramSize: "RAM Size (GB)",

    // Dashboard Results
    dashTitle: "Architecture Sizing Results",
    dashSubtitle: "Consolidated sizing metrics required for your Elasticsearch/OpenSearch cluster.",
    totalStorage: "Total Storage",
    totalMemory: "Total Memory",
    totalNodes: "Total Nodes",
    instances: "Instances",
    totalShards: "Total Shards",
    dataTiersProv: "Estimated Sizing of Data Nodes",
    noTiersConf: "No data tiers configured.",
    nodeSuffix: "Node",
    nodesSuffix: "Nodes",
    dedicatedRoles: "Sizing of Master, Machine Learning and Coordinator Nodes",
    masterNodes: "Master Nodes",
    mlNodes: "ML Nodes",
    coordNodes: "Coordinator Nodes",
    diskSuffix: "Disk",
    ramSuffix: "RAM",

    // Tier Details Labels
    volumePerDay: "Volume/Day",
    retention: "Retention",
    replicas: "Replicas",
    growth: "Growth",
    ramPerNode: "RAM/Node",
    ratio: "Ratio",
    diskPerNode: "Disk/Node",
    totalNodesLabel: "Total Nodes",

    // Print Page
    noDataFound: "No sizing data found.",
    errorLoadingData: "Error loading sizing data.",
    generatedBy: "Generated by",
    architectureTitle: "Cluster Architecture",
    loadingArchitecture: "Loading architecture diagram...",
    architectureNote: "This diagram shows the complete cluster architecture with all nodes and their resources.",
    footerText: "All rights reserved",

    // Modal
    modalTitle: "Sizing Formulas & Architecture",
    modalSource: "Official Source: Benchmarking and Sizing your Elasticsearch Cluster for Logs and Metrics",
    modalIntro: "The calculations performed by this tool use the exact mathematical logic recommended in the official Elastic documentation. Below is the breakdown of the formulas applied in real-time.",
    modalSection1: "1. Total Storage (per Tier)",
    modalSec1Desc: "The raw storage is calculated based on ingestion volume, how long it lives in the tier, and the replica multiplier. We also apply a 25% overhead factor to account for OS files, segment merges, and Elasticsearch watermark limits.",
    modalSec1Code1: "Storage (GB) = Volume/Day × Retention Days × (Replicas + 1)",
    modalSec1Code2: "Total Storage = Storage (GB) × 1.25 (Overhead) × (1 + Growth%)",

    modalSection2: "2. Required Memory",
    modalSec2Desc: "Each data tier has an optimized relationship between attached Disk capacity and required Node Memory (RAM). These default 'Ratios' can be customized in the Advanced Configurations step, but elastic defaults are:",
    modalSec2Code: "Memory (GB) = Total Storage (GB) ÷ Tier Ratio",

    modalSection3: "3. Total Nodes & JVM Limit",
    modalSec3Desc: "The amount of physical instances needed is the total required memory divided by the maximum memory provided per node.",
    modalSec3Warning: "Important JVM Constraint:",
    modalSec3WarningDesc: "Elasticsearch relies heavily on the Java Virtual Machine. The compressed object pointers (OOPs) in Java cap out efficiently at 32GB of JVM Heap. Since Elastic recommends dedicating 50% of the system RAM to Heap and 50% to the OS file system cache, a single Elasticsearch node should rarely exceed 64GB of total system RAM.",
    modalSec3Code: "Nodes = Ceil( Memory (GB) ÷ Max Node RAM )",
    modalSec3BestPractice: "Best Practice - Hot Tier:",
    modalSec3BestPracticeDesc: "The Hot tier should have a minimum of 3 nodes for high availability and fault tolerance, even if the calculation suggests fewer nodes are needed. This ensures the cluster can handle node failures without data loss or service interruption.",

    modalSection4: "4. Shards Calculation",
    modalSec4Desc: "To keep the cluster green and performing optimally, the total amount of shards is calculated by dividing the total data volume by the maximum allowed shard size (pushed to a default 50GB max).",
    modalSec4Code: "Total Shards = Ceil( Total Storage (GB) ÷ Max Shard Size )",
};

export type Translations = typeof en;
